services:
  # METAR Update Cronjob
  cronjob-update-metar:
    image: ${IMAGE_TAG_NAME}:${IMAGE_VERSION}
    container_name: ${NAME_PREFIX:-salko}-cronjob-update-metar-${BRANCH_SUFFIX:-dev}
    networks:
      - internal_dev
    env_file: ../.env.dev
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@${NAME_PREFIX}-postgres-${BRANCH_SUFFIX}:${PGPORT}/${POSTGRES_DB}
    restart: "no"

networks:
  internal_dev:
    external: true
    name: salko_dev_internal
